image: node:latest

stages:
  - lint
  - test

lint_frontend:
  stage: lint
  script:
    # Go into frontend
    - cd frontend
    # Install requirements
    - npm install
    # Run linting
    - npm run lint

unit_tests_frontend:
  stage: test
  script:
    # Go into frontend
    - cd frontend
    # Install requirements
    - npm install
    # Run tests
    - npm run test
