image: node:latest

stages:
  - lint
  - test

lint_frontend:
  stage: lint
  script:
    # Go into frontend
    - cd frontend
    # Install requirements
    - npm install
    # Run linting
    - npm run lint

unit_tests_frontend:
  stage: test
  script:
    # Go into frontend
    - cd frontend
    # Install requirements
    - npm install
    # Run tests
    - npm run test

lint_backend:
  stage: lint
  script:
    # Go into frontend
    - cd backend
    # Install requirements
    - python -m pip install pylint
    # Run linting
    - python -m pylint .

unit_tests_backend:
  stage: test
  image: "python:3.7"
  script:
    - cd backend
    - pip install -r requirements.txt
    - python manage.py test
