image: node:latest

stages:
  - lint

eslint:
  stage: lint
  script:
    # Go into frontend
    - cd frontend
    # Install ESLint in this docker container
    - npm install
    # Run ESLint
    - npm run lint
